version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      - type: bind
        source: ./instance
        target: /app/instance
    env_file:
      - .env
    environment:
      - GUNICORN_CMD_ARGS=--access-logfile=- --error-logfile=- --reload
      - SQLALCHEMY_DATABASE_URI=${DB_URI}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    restart: always
