version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      - GUNICORN_CMD_ARGS="--access-logfile=- --error-logfile=- --reload"
    restart: always
